### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by blister1824** [ThibaultGROUEIX/AtlasNet#8]
I try to run the script `./training/train_AE_AtlasNet.py` but I get the error `RuntimeError: cuda runtime error (2) : out of memory`. It seems that my GPU runs out of memory. So I try tot set the arg `batchSzie` smaller but it still meets this error(with more epochs though). I use the code `network = nn.DataParallel(network)` trying  to solve this problem but i got another error `Expected more than 1 value per channel when training, got input size [1, 1024]`.
My device is GeForce GTX 1080 and I have 8 GPUS. So i don't think memory should be a problem.
_HINT" I am a newer to DL and fresh to pytorch and i hope i don't disturb u_

**Comment by ThibaultGROUEIX** [comment]
Hello, Can you provide:
- pytorch version
- GPU memory
- full log

**Comment by rpetar** [comment]
I'm using **Torch 0.4.0.** If you have this warning:

`UserWarning: volatile was removed and now has no effect. Use 'with torch.no_grad():' instead.`

try to replace this part in `train_AE_AtlasNet.py `_(line 172)_:

```
for i, data in enumerate(dataloader_test, 0):
    img, points, cat, _ , _ = data
    points = Variable(points, volatile=True)
```

with:

```
with torch.no_grad():
    for i, data in enumerate(dataloader_test, 0):
        img, points, cat, _, _ = data
        # remove line below
        # points = Variable(points, volatile= True)
        points = points.transpose(2,  1).contiguous()
        # remaining is the same
```

This worked for me.

**Comment by ThibaultGROUEIX** [comment]
Thanks @rpetar : I guess this works if you use pytorch v4. I am not including it in the code, as I recommend using v1.12 in the README but i bet your comment will be useful ! Thanks

**Comment by blister1824** [comment]
@ThibaultGROUEIX The full information is followed:

- Torch 

> Version:0.4.0

-GPU memory: 

> GeForce

 GTX 1080,8GB

- full log:
> HCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524577523076/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 181, in <module>
    pointsReconstructed  = network(points)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/model.py", line 239, in forward
    x = self.encoder(x)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/model.py", line 84, in forward
    x = self.bn3(self.conv3(x))
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524577523076/work/aten/src/THC/generic/THCStorage.cu:58

**Comment by blister1824** [comment]
@ThibaultGROUEIX The full information is followed:

-Torch Version:
> 0.4.0

-GPU memory:
> GeForce GTX 1080,8GB

-full log:
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524577523076/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "./training/train_AE_AtlasNet.py", line 181, in <module>
    pointsReconstructed  = network(points)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/model.py", line 239, in forward
    x = self.encoder(x)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/model.py", line 84, in forward
    x = self.bn3(self.conv3(x))
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/wangzijie/anaconda2/envs/pytorch-atlasnet/lib/python2.7/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524577523076/work/aten/src/THC/generic/THCStorage.cu:58

**Comment by ThibaultGROUEIX** [comment]
@blister1824 you should then try @rpetar 's solution.

**Comment by ThibaultGROUEIX** [comment]
@blister1824 Did you made it work with @rpetar 's solution ?
